ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/Assistance_Request__c.object-meta.xml
<CustomObject>
    <description>The Assistance Request object stores your requests for assistance using the Artisan Assistance application.</description>
    <label>Assistance Request</label>
    <nameField>
        <displayFormat>REQ{00000000}</displayFormat>
        <label>Request Ref#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>OR(
ISPICKVAL( Phase__c, &#39;Estimation&#39; ),
ISPICKVAL( Phase__c, &#39;Development&#39; ),
ISPICKVAL( Phase__c, &#39;Test&#39; ),
ISPICKVAL( Phase__c, &#39;Deployment&#39; ),
ISPICKVAL( Phase__c, &#39;Acceptance&#39; ),
ISPICKVAL( Stage_Name__c, &#39;Waiting for Clarification&#39; )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether the Assistance Request is still active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Production_Deployment__c.field-meta.xml
<CustomField>
    <fullName>Production_Deployment__c</fullName>
    <inlineHelpText>If the work is to be completed in a sandbox do you require us to deploy changes to production after testing?</inlineHelpText>
    <label>Production Deployment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Stage_Name__c</fullName>
    <defaultValue>&#39;Drafting&#39;</defaultValue>
    <inlineHelpText>The current stage in the delivery process for this Request for Assistance.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drafting</fullName>
                <default>true</default>
                <label>Drafting</label>
            </value>
            <value>
                <fullName>Waiting for Estimation</fullName>
            </value>
            <value>
                <fullName>Being Estimated</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Waiting for Development</fullName>
            </value>
            <value>
                <fullName>Being Developed</fullName>
            </value>
            <value>
                <fullName>Waiting for Testing</fullName>
            </value>
            <value>
                <fullName>Being Tested</fullName>
            </value>
            <value>
                <fullName>Waiting for Deployment</fullName>
            </value>
            <value>
                <fullName>Being Deployed</fullName>
            </value>
            <value>
                <fullName>Waiting for Acceptance</fullName>
            </value>
            <value>
                <fullName>Accepted as Complete</fullName>
            </value>
            <value>
                <fullName>Waiting for Clarification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/classes/AssistanceRequestController.cls
/**
 * Artisan Assist Assistance Request controller
 * 
 * Controller class for the aura components
 * 
 * @author Richard Clarke
 * @date 05/08/2019
 */
public with sharing class AssistanceRequestController {
    
    // Change the stage
    @AuraEnabled
    public static void setNewStageNameApex( String arId, String newStageName ){
//system.debug('In AssistanceRequestController.setNewStageNameApex with Id [' + arId + '] and newStageName [' + newStageName + ']');
        
        // M.Witchalls 18 Oct 2019 Check to make sure all fields are accessible to this user and updateable by this user
        try {

            // M.Witchalls 18 Oct 2019
            SecurityUtils.checkRead(
                Assistance_Request__c.sObjectType, 
			    new List<SObjectField> {
                	Assistance_Request__c.Stage_Name__c
                }
		    );
            SecurityUtils.checkUpdate(
                Assistance_Request__c.sObjectType, 
			    new List<SObjectField> {
                 	Assistance_Request__c.Stage_Name__c
                }
		    );

            List<Assistance_Request__c> reqs = [SELECT Id, Stage_Name__c FROM Assistance_Request__c WHERE Id=:arId FOR UPDATE];

            if ( reqs.size() != 1 ){
                throw new Utils.IntegrationException('Unable to locate the Assistance Request [' + arId + ']');
            }

            reqs[0].Stage_Name__c = newStageName;
            UPDATE reqs[0];
        } catch (Exception e) {
            Logutils.log(e, 'Failed to set the Assistance Request stage name to [' + newStageName + ']');
        }                
    }
    
    // Poll Artisan org now
    @AuraEnabled
    public static void pollArtisanNowApex( String arId ){
//system.debug('In AssistanceRequestController.pollArtisanNowApex with Id [' + arId + ']');
        try {
            AssistanceRequestUpdatePolling.PollArtisanOrgForUpdate( arId );
        } catch (Exception e) {
            Logutils.log(e, 'Failed to poll Artisan for updates to Assistance Request Id [' + arId + ']');
        }                
    }
    
    // Return the current namespace
    @AuraEnabled
    public static String getNameSpace(){
        return Utils.GetNamespacePrefix();
    }
    
    // Return the request for assistance with the fields populated which are needed to control button visibility
    // This was implemented because the use of recordData would not reload when the record was changed either by
    // a user's edit action or by a serverside refresh from the polling API
    @AuraEnabled
    public static Assistance_Request__c getAssistanceRequest( String arId ){
        
        // M.Witchalls 18 Oct 2019 Check to make sure all fields are accessible to this user
        List<Assistance_Request__c> reqs = new List<Assistance_Request__c>();     

        try {
            SecurityUtils.checkRead(
                Assistance_Request__c.sObjectType, 
			    new List<SObjectField> {
                	Assistance_Request__c.Stage_Name__c,
                	Assistance_Request__c.IsActive__c,
                	Assistance_Request__c.Production_Deployment__c
                }
		    );

            reqs = [select Id, Stage_Name__c, IsActive__c, Production_Deployment__c from Assistance_Request__c READONLY where Id = :arId LIMIT 1];

        } catch (Exception e) {
            Logutils.log(e, 'Failed to read Assistance Request Id [' + arId + ']');
        } 

        return reqs[0];
    }
}