ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/Assistance_Request__c.object-meta.xml
<CustomObject>
    <description>The Assistance Request object stores your requests for assistance using the Artisan Assistance application.</description>
    <label>Assistance Request</label>
    <nameField>
        <displayFormat>REQ{00000000}</displayFormat>
        <label>Request Ref#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Date_Required__c.field-meta.xml
<CustomField>
    <fullName>Date_Required__c</fullName>
    <inlineHelpText>When do you need this completed by (leave blank if not known)</inlineHelpText>
    <label>Required by Date</label>
    <type>Date</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Describe what business outcome you need to achieve together with any technical insights about how you want the work to be done</inlineHelpText>
    <label>Business Outcome Required</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Login_Access__c.field-meta.xml
<CustomField>
    <fullName>Login_Access__c</fullName>
    <inlineHelpText>Have you provided login access?</inlineHelpText>
    <label>Login Access</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Preferred_Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Billing_Currency__c</fullName>
    <inlineHelpText>In which currency would you prefer to be billed in once the work is complete?</inlineHelpText>
    <label>Preferred Billing Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AED - UAE Dirham</fullName>
            </value>
            <value>
                <fullName>AFN - Afghanistan Afghani (New)</fullName>
            </value>
            <value>
                <fullName>ALL - Albanian Lek</fullName>
            </value>
            <value>
                <fullName>AMD - Armenian Dram</fullName>
            </value>
            <value>
                <fullName>ANG - Neth Antilles Guilder</fullName>
            </value>
            <value>
                <fullName>AOA - Angola Kwanza</fullName>
            </value>
            <value>
                <fullName>ARS - Argentine Peso</fullName>
            </value>
            <value>
                <fullName>AUD - Australian Dollar</fullName>
                <default>true</default>
                <label>AUD - Australian Dollar</label>
            </value>
            <value>
                <fullName>AWG - Aruba Florin</fullName>
            </value>
            <value>
                <fullName>AZN - Azerbaijan Manat</fullName>
            </value>
            <value>
                <fullName>BAM - Convertible Marks</fullName>
            </value>
            <value>
                <fullName>BBD - Barbados Dollar</fullName>
            </value>
            <value>
                <fullName>BDT - Bangladesh Taka</fullName>
            </value>
            <value>
                <fullName>BGN - Bulgarian Lev</fullName>
            </value>
            <value>
                <fullName>BHD - Bahraini Dinar</fullName>
            </value>
            <value>
                <fullName>BIF - Burundi Franc</fullName>
            </value>
            <value>
                <fullName>BMD - Bermuda Dollar</fullName>
            </value>
            <value>
                <fullName>BND - Brunei Dollar</fullName>
            </value>
            <value>
                <fullName>BOB - Bolivian Boliviano</fullName>
            </value>
            <value>
                <fullName>BOV - Bolivia Mvdol</fullName>
            </value>
            <value>
                <fullName>BRB - Brazilian Cruzeiro (old)</fullName>
            </value>
            <value>
                <fullName>BRL - Brazilian Real</fullName>
            </value>
            <value>
                <fullName>BSD - Bahamian Dollar</fullName>
            </value>
            <value>
                <fullName>BTN - Bhutan Ngultrum</fullName>
            </value>
            <value>
                <fullName>BWP - Botswana Pula</fullName>
            </value>
            <value>
                <fullName>BYN - Belarusian Ruble</fullName>
            </value>
            <value>
                <fullName>BYR - Belarusian Ruble</fullName>
            </value>
            <value>
                <fullName>BZD - Belize Dollar</fullName>
            </value>
            <value>
                <fullName>CAD - Canadian Dollar</fullName>
            </value>
            <value>
                <fullName>CDF - Franc Congolais</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Preferred_Resource_Location__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Resource_Location__c</fullName>
    <inlineHelpText>In which location would you prefer the resources allocated to this request for assistance to be based</inlineHelpText>
    <label>Preferred Resource Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No preference</fullName>
                <default>true</default>
                <label>No preference</label>
            </value>
            <value>
                <fullName>In my office</fullName>
            </value>
            <value>
                <fullName>In my city</fullName>
            </value>
            <value>
                <fullName>In my state</fullName>
            </value>
            <value>
                <fullName>In my country</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Preferred_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Timezone__c</fullName>
    <inlineHelpText>In what timezone do you prefer to be contacted?</inlineHelpText>
    <label>Preferred Timezone</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(GMT+14:00) Line Islands Time (Pacific/Kiritimati)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) Phoenix Islands Time (Pacific/Enderbury)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) Tonga Standard Time (Pacific/Tongatapu)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:45) Chatham Standard Time (Pacific/Chatham)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Petropavlovsk-Kamchatski Standard Time (Asia/Kamchatka)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) New Zealand Standard Time (Pacific/Auckland)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Fiji Standard Time (Pacific/Fiji)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Solomon Islands Time (Pacific/Guadalcanal)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Norfolk Island Time (Pacific/Norfolk)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:30) Lord Howe Standard Time (Australia/Lord_Howe)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:00) Australian Eastern Standard Time (Australia/Brisbane)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:00) Australian Eastern Standard Time (Australia/Sydney)</fullName>
                <default>true</default>
                <label>(GMT+10:00) Australian Eastern Standard Time (Australia/Sydney)</label>
            </value>
            <value>
                <fullName>(GMT+09:30) Australian Central Standard Time (Australia/Adelaide)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:30) Australian Central Standard Time (Australia/Darwin)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Korean Standard Time (Asia/Seoul)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Japan Standard Time (Asia/Tokyo)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Hong Kong Standard Time (Asia/Hong_Kong)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Malaysia Time (Asia/Kuala_Lumpur)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Philippine Standard Time (Asia/Manila)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) China Standard Time (Asia/Shanghai)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Singapore Standard Time (Asia/Singapore)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Taipei Standard Time (Asia/Taipei)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Australian Western Standard Time (Australia/Perth)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Indochina Time (Asia/Bangkok)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Indochina Time (Asia/Ho_Chi_Minh)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Western Indonesia Time (Asia/Jakarta)</fullName>
            </value>
            <value>
                <fullName>(GMT+06:30) Myanmar Time (Asia/Rangoon)</fullName>
            </value>
            <value>
                <fullName>(GMT+06:00) Bangladesh Standard Time (Asia/Dhaka)</fullName>
            </value>
            <value>
                <fullName>(GMT+05:45) Nepal Time (Asia/Kathmandu)</fullName>
            </value>
            <value>
                <fullName>(GMT+05:30) India Standard Time (Asia/Colombo)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Prior_Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Prior_Stage_Name__c</fullName>
    <inlineHelpText>The name of the prior stage excluding Waiting for Clarification (used to control what stage name should be used when all open questions are answered)</inlineHelpText>
    <label>Prior Stage</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Salesforce_Product__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Product__c</fullName>
    <inlineHelpText>Which Salesforce Product is primarily involved with this change?</inlineHelpText>
    <label>Salesforce Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analytics Cloud (Einstein Analytics)</fullName>
            </value>
            <value>
                <fullName>Analytics Cloud (Tableau)</fullName>
            </value>
            <value>
                <fullName>App Cloud (Heroku)</fullName>
            </value>
            <value>
                <fullName>App Cloud (Salesforce Platform)</fullName>
            </value>
            <value>
                <fullName>AppExchange Application(s)</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud (CloudCraze)</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud (DemandWare)</fullName>
            </value>
            <value>
                <fullName>Community Cloud</fullName>
            </value>
            <value>
                <fullName>CPQ (Steelbrick)</fullName>
            </value>
            <value>
                <fullName>Integration Cloud (Mule)</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud (ExactTarget)</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud (Pardot)</fullName>
            </value>
            <value>
                <fullName>Sales Cloud</fullName>
                <default>true</default>
                <label>Sales Cloud</label>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Stage_Name__c</fullName>
    <defaultValue>&#39;Drafting&#39;</defaultValue>
    <inlineHelpText>The current stage in the delivery process for this Request for Assistance.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drafting</fullName>
                <default>true</default>
                <label>Drafting</label>
            </value>
            <value>
                <fullName>Waiting for Estimation</fullName>
            </value>
            <value>
                <fullName>Being Estimated</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Waiting for Development</fullName>
            </value>
            <value>
                <fullName>Being Developed</fullName>
            </value>
            <value>
                <fullName>Waiting for Testing</fullName>
            </value>
            <value>
                <fullName>Being Tested</fullName>
            </value>
            <value>
                <fullName>Waiting for Deployment</fullName>
            </value>
            <value>
                <fullName>Being Deployed</fullName>
            </value>
            <value>
                <fullName>Waiting for Acceptance</fullName>
            </value>
            <value>
                <fullName>Accepted as Complete</fullName>
            </value>
            <value>
                <fullName>Waiting for Clarification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/classes/AssistanceRequestReplicationTest.cls
/**
 * Artisan Assistance class to handle testing assistance request object insert/update with supporting trigger and platform event functionality
 *
 * @author Richard Clarke
 * @date 29/07/2019
 */
@isTest
public class AssistanceRequestReplicationTest {
    
    // Test the handling when a Request for Assistance is created then updated and works as it should
    static testMethod void testRequestInsertUpdate_ExpectedBehaviour() {
         // Setup callout mock response
        string mockResponseBody = '{\"Case.Id\":\"5000p00000Dv7TnAAJ\"}';
        Map<String, String> responseHeaders =  new Map<String, String> ();
        responseHeaders.put('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, new ArtisanRestApiCalloutsMock(200, mockResponseBody, responseHeaders));

        Test.startTest();
        
        // Create a new request for assistance
        Assistance_Request__c req = new Assistance_Request__c(
            Description__c = 'I need some help',
            Login_Access__c = 'Yes',
            Preferred_Billing_Currency__c = 'AUD - Australian Dollar',
            Preferred_Resource_Location__c = 'No preference',
            Preferred_Timezone__c = '(GMT+10:00) Australian Eastern Standard Time (Australia/Sydney)',
            Prior_Stage_Name__c = null,
            Date_Required__c = Date.today().addMonths(1),
            Salesforce_Product__c = 'Sales Cloud',
            Sandbox_Name__c = null,
            Stage_Name__c = 'Drafting',
            Success_Criteria__c = 'So I will know what to do',
            Title__c = 'Please help me',
            Urgency__c = 'Medium');
        insert req;

        // Update it to the next stage
		req = [
            select Id, Name, Description__c, Login_Access__c, Preferred_Billing_Currency__c, Preferred_Resource_Location__c, Preferred_Timezone__c,
            	Prior_Stage_Name__c, Date_Required__c, Salesforce_Product__c, Sandbox_Name__c, Stage_Name__c, Success_Criteria__c, Phase__c, 
            	Title__c, Urgency__c, Sync_Status__c 
            from Assistance_Request__c 
            where Id = :req.Id 
            limit 1 
            for update][0];
        
        req.Description__c = 'I need a lot of help!';
        req.Prior_Stage_Name__c = 'Drafting';
        req.Stage_Name__c = 'Waiting for Estimation';
        
        update req;

        Test.stopTest();

        // Read back the final outcome
		Assistance_Request__c updatedReq = [
            select Id, Name, Description__c, Login_Access__c, Preferred_Billing_Currency__c, Preferred_Resource_Location__c, Preferred_Timezone__c,
            	Prior_Stage_Name__c, Date_Required__c, Salesforce_Product__c, Sandbox_Name__c, Stage_Name__c, Success_Criteria__c, Phase__c, 
            	Title__c, Urgency__c, Sync_Status__c, Sync_Details__c
            from Assistance_Request__c 
            where Id = :req.Id 
            limit 1][0];

        // Insert trigger should have published an insert and the event subscriber/trigger should have called the API and updated the sync details
        system.assertEquals(updatedReq.Sync_Status__c , 'Sync successful', 'Expecting the request to be updated reflecting data is in sync');
        system.assertEquals(updatedReq.Sync_Details__c.left(17), 'Artisan Case Id=[', 'Expecting the request to be updated with the Case Id from the sync');
        
        // Quickly test the Apex controller for the lightning component
        system.assertEquals(Utils.GetNamespacePrefix(), AssistanceRequestController.getNameSpace(), 'Apex controller for component should return the namespace');
        Assistance_Request__c controllerReq = AssistanceRequestController.getAssistanceRequest(req.Id);
        system.assertEquals(req.Id,controllerReq.Id,'Apex controller for component should be able to retrieve the request record');
    }
    
    // Test the handling when a Request for Assistance fails when during the insert sync due to the API returning an exception
    static testMethod void testRequestInsert_ExceptionBehaviour() {
         // Setup callout mock response
        string mockResponseBody = '{\"Exception\":\"Assistance_Request_Id is required\"}';
        Map<String, String> responseHeaders =  new Map<String, String> ();
        responseHeaders.put('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, new ArtisanRestApiCalloutsMock(404, mockResponseBody, responseHeaders));

        Test.startTest();
        
        // Create a new request for assistance
        Assistance_Request__c req = new Assistance_Request__c(
            Description__c = 'I need some help',
            Login_Access__c = 'Yes',
            Preferred_Billing_Currency__c = 'AUD - Australian Dollar',
            Preferred_Resource_Location__c = 'No preference',
            Preferred_Timezone__c = '(GMT+10:00) Australian Eastern Standard Time (Australia/Sydney)',
            Prior_Stage_Name__c = null,
            Date_Required__c = Date.today().addMonths(1),
            Salesforce_Product__c = 'Sales Cloud',
            Sandbox_Name__c = null,
            Stage_Name__c = 'Drafting',
            Success_Criteria__c = 'So I will know what to do',
            Title__c = 'Please help me',
            Urgency__c = 'Medium');
        insert req;

        Test.stopTest();

        // Read back the final outcome
		Assistance_Request__c updatedReq = [
            select Id, Name, Description__c, Login_Access__c, Preferred_Billing_Currency__c, Preferred_Resource_Location__c, Preferred_Timezone__c,
            	Prior_Stage_Name__c, Date_Required__c, Salesforce_Product__c, Sandbox_Name__c, Stage_Name__c, Success_Criteria__c, Phase__c, 
            	Title__c, Urgency__c, Sync_Status__c, Sync_Details__c
            from Assistance_Request__c 
            where Id = :req.Id 
            limit 1][0];

        // Insert trigger should have published an insert and the event subscriber/trigger should have called the API and updated the sync details
        system.assertEquals(updatedReq.Sync_Status__c , 'Sync failed', 'Expecting the request to be updated reflecting data is not in sync');
        system.assertEquals(updatedReq.Sync_Details__c.contains('The callout to ArtisanRestApiCallouts.insertAssistanceRequest failed to replicate Assistance Request with Id'), true, 'Expecting the sync details to contain the exception [' + updatedReq.Sync_Details__c + ']');
    }
    
    // Test the handling when a Request for Assistance is created then updated and works as it should
    static testMethod void testRequestUpdate_ExpectedBehaviour() {
         // Setup callout mock response
        string mockResponseBody = '{\"Case.Id\":\"5000p00000Dv7TnAAJ\"}';
        Map<String, String> responseHeaders =  new Map<String, String> ();
        responseHeaders.put('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, new ArtisanRestApiCalloutsMock(200, mockResponseBody, responseHeaders));

        // Create a new request for assistance
        Assistance_Request__c req = new Assistance_Request__c(
            Description__c = 'I need some help',
            Login_Access__c = 'Yes',
            Preferred_Billing_Currency__c = 'AUD - Australian Dollar',
            Preferred_Resource_Location__c = 'No preference',
            Preferred_Timezone__c = '(GMT+10:00) Australian Eastern Standard Time (Australia/Sydney)',
            Prior_Stage_Name__c = null,
            Date_Required__c = Date.today().addMonths(1),
            Salesforce_Product__c = 'Sales Cloud',
            Sandbox_Name__c = null,
            Stage_Name__c = 'Drafting',
            Success_Criteria__c = 'So I will know what to do',
            Title__c = 'Please help me',
            Urgency__c = 'Medium');
        insert req;

        Test.startTest();

         // Setup callout mock response
        string exceptionMockResponseBody = '{\"Exception\":\"Assistance_Request_Id is required\"}';
        Map<String, String> exceptionResponseHeaders =  new Map<String, String> ();
        exceptionResponseHeaders.put('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, new ArtisanRestApiCalloutsMock(404, exceptionMockResponseBody, exceptionResponseHeaders));

        // Update it to the next stage
		req = [
            select Id, Name, Description__c, Login_Access__c, Preferred_Billing_Currency__c, Preferred_Resource_Location__c, Preferred_Timezone__c,
            	Prior_Stage_Name__c, Date_Required__c, Salesforce_Product__c, Sandbox_Name__c, Stage_Name__c, Success_Criteria__c, Phase__c, 
            	Title__c, Urgency__c, Sync_Status__c 
            from Assistance_Request__c 
            where Id = :req.Id 
            limit 1 
            for update][0];
        
        req.Description__c = 'I need a lot of help!';
        req.Prior_Stage_Name__c = 'Drafting';
        
        update req;

        AssistanceRequestController.setNewStageNameApex( req.Id, req.Stage_Name__c = 'Waiting for Estimation' );

        Test.stopTest();

        // Read back the final outcome
		Assistance_Request__c updatedReq = [
            select Id, Name, Description__c, Login_Access__c, Preferred_Billing_Currency__c, Preferred_Resource_Location__c, Preferred_Timezone__c,
            	Prior_Stage_Name__c, Date_Required__c, Salesforce_Product__c, Sandbox_Name__c, Stage_Name__c, Success_Criteria__c, Phase__c, 
            	Title__c, Urgency__c, Sync_Status__c, Sync_Details__c
            from Assistance_Request__c 
            where Id = :req.Id 
            limit 1][0];

        // Insert trigger should have published an insert and the event subscriber/trigger should have called the API and updated the sync details
        system.assertEquals(updatedReq.Sync_Status__c , 'Sync failed', 'Expecting the request to be updated reflecting data is not in sync');
        system.assertEquals(updatedReq.Sync_Details__c.contains('The callout to ArtisanRestApiCallouts.updateAssistanceRequest failed to replicate Assistance Request with Id'), true, 'Expecting the sync details to contain the exception [' + updatedReq.Sync_Details__c + ']');
    }
    
    // Test the handling of the code which sets the phase from the stage name
    static testMethod void testPhaseFromStageName() {
        system.assertEquals( 'Estimation', AssistanceRequestReplication.PhaseFromStageName( 'Waiting for Clarification', 'Waiting for Approval' ));
        
        system.assertEquals( 'Draft', AssistanceRequestReplication.PhaseFromStageName( 'Drafting', null ));
        
        system.assertEquals( 'Estimation', AssistanceRequestReplication.PhaseFromStageName( 'Waiting for Estimation', null ));
        system.assertEquals( 'Estimation', AssistanceRequestReplication.PhaseFromStageName( 'Being Estimated', null ));
        system.assertEquals( 'Estimation', AssistanceRequestReplication.PhaseFromStageName( 'Waiting for Approval', null ));

        system.assertEquals( 'Development', AssistanceRequestReplication.PhaseFromStageName( 'Waiting for Development', null ));
        system.assertEquals( 'Development', AssistanceRequestReplication.PhaseFromStageName( 'Being Developed', null ));
                                                                                       
        system.assertEquals( 'Test', AssistanceRequestReplication.PhaseFromStageName( 'Waiting for Testing', null ));
        system.assertEquals( 'Test', AssistanceRequestReplication.PhaseFromStageName( 'Being Tested', null ));

        system.assertEquals( 'Deployment', AssistanceRequestReplication.PhaseFromStageName( 'Waiting for Deployment', null ));
        system.assertEquals( 'Deployment', AssistanceRequestReplication.PhaseFromStageName( 'Being Deployed', null ));

        system.assertEquals( 'Acceptance', AssistanceRequestReplication.PhaseFromStageName( 'Waiting for Acceptance', null ));

        system.assertEquals( 'Completed', AssistanceRequestReplication.PhaseFromStageName( 'Accepted as Complete', null ));

        system.assertEquals( 'Cancelled', AssistanceRequestReplication.PhaseFromStageName( 'Declined', null ));
        system.assertEquals( 'Cancelled', AssistanceRequestReplication.PhaseFromStageName( 'Rejected', null ));
    }
 }