ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/Assistance_Request__c.object-meta.xml
<CustomObject>
    <description>The Assistance Request object stores your requests for assistance using the Artisan Assistance application.</description>
    <label>Assistance Request</label>
    <nameField>
        <displayFormat>REQ{00000000}</displayFormat>
        <label>Request Ref#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Date_Required__c.field-meta.xml
<CustomField>
    <fullName>Date_Required__c</fullName>
    <inlineHelpText>When do you need this completed by (leave blank if not known)</inlineHelpText>
    <label>Required by Date</label>
    <type>Date</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Describe what business outcome you need to achieve together with any technical insights about how you want the work to be done</inlineHelpText>
    <label>Business Outcome Required</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Login_Access__c.field-meta.xml
<CustomField>
    <fullName>Login_Access__c</fullName>
    <inlineHelpText>Have you provided login access?</inlineHelpText>
    <label>Login Access</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Preferred_Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Billing_Currency__c</fullName>
    <inlineHelpText>In which currency would you prefer to be billed in once the work is complete?</inlineHelpText>
    <label>Preferred Billing Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AED - UAE Dirham</fullName>
            </value>
            <value>
                <fullName>AFN - Afghanistan Afghani (New)</fullName>
            </value>
            <value>
                <fullName>ALL - Albanian Lek</fullName>
            </value>
            <value>
                <fullName>AMD - Armenian Dram</fullName>
            </value>
            <value>
                <fullName>ANG - Neth Antilles Guilder</fullName>
            </value>
            <value>
                <fullName>AOA - Angola Kwanza</fullName>
            </value>
            <value>
                <fullName>ARS - Argentine Peso</fullName>
            </value>
            <value>
                <fullName>AUD - Australian Dollar</fullName>
                <default>true</default>
                <label>AUD - Australian Dollar</label>
            </value>
            <value>
                <fullName>AWG - Aruba Florin</fullName>
            </value>
            <value>
                <fullName>AZN - Azerbaijan Manat</fullName>
            </value>
            <value>
                <fullName>BAM - Convertible Marks</fullName>
            </value>
            <value>
                <fullName>BBD - Barbados Dollar</fullName>
            </value>
            <value>
                <fullName>BDT - Bangladesh Taka</fullName>
            </value>
            <value>
                <fullName>BGN - Bulgarian Lev</fullName>
            </value>
            <value>
                <fullName>BHD - Bahraini Dinar</fullName>
            </value>
            <value>
                <fullName>BIF - Burundi Franc</fullName>
            </value>
            <value>
                <fullName>BMD - Bermuda Dollar</fullName>
            </value>
            <value>
                <fullName>BND - Brunei Dollar</fullName>
            </value>
            <value>
                <fullName>BOB - Bolivian Boliviano</fullName>
            </value>
            <value>
                <fullName>BOV - Bolivia Mvdol</fullName>
            </value>
            <value>
                <fullName>BRB - Brazilian Cruzeiro (old)</fullName>
            </value>
            <value>
                <fullName>BRL - Brazilian Real</fullName>
            </value>
            <value>
                <fullName>BSD - Bahamian Dollar</fullName>
            </value>
            <value>
                <fullName>BTN - Bhutan Ngultrum</fullName>
            </value>
            <value>
                <fullName>BWP - Botswana Pula</fullName>
            </value>
            <value>
                <fullName>BYN - Belarusian Ruble</fullName>
            </value>
            <value>
                <fullName>BYR - Belarusian Ruble</fullName>
            </value>
            <value>
                <fullName>BZD - Belize Dollar</fullName>
            </value>
            <value>
                <fullName>CAD - Canadian Dollar</fullName>
            </value>
            <value>
                <fullName>CDF - Franc Congolais</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Preferred_Resource_Location__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Resource_Location__c</fullName>
    <inlineHelpText>In which location would you prefer the resources allocated to this request for assistance to be based</inlineHelpText>
    <label>Preferred Resource Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No preference</fullName>
                <default>true</default>
                <label>No preference</label>
            </value>
            <value>
                <fullName>In my office</fullName>
            </value>
            <value>
                <fullName>In my city</fullName>
            </value>
            <value>
                <fullName>In my state</fullName>
            </value>
            <value>
                <fullName>In my country</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Preferred_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Timezone__c</fullName>
    <inlineHelpText>In what timezone do you prefer to be contacted?</inlineHelpText>
    <label>Preferred Timezone</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(GMT+14:00) Line Islands Time (Pacific/Kiritimati)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) Phoenix Islands Time (Pacific/Enderbury)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) Tonga Standard Time (Pacific/Tongatapu)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:45) Chatham Standard Time (Pacific/Chatham)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Petropavlovsk-Kamchatski Standard Time (Asia/Kamchatka)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) New Zealand Standard Time (Pacific/Auckland)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Fiji Standard Time (Pacific/Fiji)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Solomon Islands Time (Pacific/Guadalcanal)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Norfolk Island Time (Pacific/Norfolk)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:30) Lord Howe Standard Time (Australia/Lord_Howe)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:00) Australian Eastern Standard Time (Australia/Brisbane)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:00) Australian Eastern Standard Time (Australia/Sydney)</fullName>
                <default>true</default>
                <label>(GMT+10:00) Australian Eastern Standard Time (Australia/Sydney)</label>
            </value>
            <value>
                <fullName>(GMT+09:30) Australian Central Standard Time (Australia/Adelaide)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:30) Australian Central Standard Time (Australia/Darwin)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Korean Standard Time (Asia/Seoul)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Japan Standard Time (Asia/Tokyo)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Hong Kong Standard Time (Asia/Hong_Kong)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Malaysia Time (Asia/Kuala_Lumpur)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Philippine Standard Time (Asia/Manila)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) China Standard Time (Asia/Shanghai)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Singapore Standard Time (Asia/Singapore)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Taipei Standard Time (Asia/Taipei)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Australian Western Standard Time (Australia/Perth)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Indochina Time (Asia/Bangkok)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Indochina Time (Asia/Ho_Chi_Minh)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Western Indonesia Time (Asia/Jakarta)</fullName>
            </value>
            <value>
                <fullName>(GMT+06:30) Myanmar Time (Asia/Rangoon)</fullName>
            </value>
            <value>
                <fullName>(GMT+06:00) Bangladesh Standard Time (Asia/Dhaka)</fullName>
            </value>
            <value>
                <fullName>(GMT+05:45) Nepal Time (Asia/Kathmandu)</fullName>
            </value>
            <value>
                <fullName>(GMT+05:30) India Standard Time (Asia/Colombo)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Prior_Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Prior_Stage_Name__c</fullName>
    <inlineHelpText>The name of the prior stage excluding Waiting for Clarification (used to control what stage name should be used when all open questions are answered)</inlineHelpText>
    <label>Prior Stage</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Salesforce_Product__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Product__c</fullName>
    <inlineHelpText>Which Salesforce Product is primarily involved with this change?</inlineHelpText>
    <label>Salesforce Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analytics Cloud (Einstein Analytics)</fullName>
            </value>
            <value>
                <fullName>Analytics Cloud (Tableau)</fullName>
            </value>
            <value>
                <fullName>App Cloud (Heroku)</fullName>
            </value>
            <value>
                <fullName>App Cloud (Salesforce Platform)</fullName>
            </value>
            <value>
                <fullName>AppExchange Application(s)</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud (CloudCraze)</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud (DemandWare)</fullName>
            </value>
            <value>
                <fullName>Community Cloud</fullName>
            </value>
            <value>
                <fullName>CPQ (Steelbrick)</fullName>
            </value>
            <value>
                <fullName>Integration Cloud (Mule)</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud (ExactTarget)</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud (Pardot)</fullName>
            </value>
            <value>
                <fullName>Sales Cloud</fullName>
                <default>true</default>
                <label>Sales Cloud</label>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Stage_Name__c</fullName>
    <defaultValue>&#39;Drafting&#39;</defaultValue>
    <inlineHelpText>The current stage in the delivery process for this Request for Assistance.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drafting</fullName>
                <default>true</default>
                <label>Drafting</label>
            </value>
            <value>
                <fullName>Waiting for Estimation</fullName>
            </value>
            <value>
                <fullName>Being Estimated</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Waiting for Development</fullName>
            </value>
            <value>
                <fullName>Being Developed</fullName>
            </value>
            <value>
                <fullName>Waiting for Testing</fullName>
            </value>
            <value>
                <fullName>Being Tested</fullName>
            </value>
            <value>
                <fullName>Waiting for Deployment</fullName>
            </value>
            <value>
                <fullName>Being Deployed</fullName>
            </value>
            <value>
                <fullName>Waiting for Acceptance</fullName>
            </value>
            <value>
                <fullName>Accepted as Complete</fullName>
            </value>
            <value>
                <fullName>Waiting for Clarification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/classes/AssistanceRequestControllerTest.cls
/**
 * Artisan Assistance class to test AssistanceRequestController.cls
 *
 * @author Michael Witchalls
 * @date 18/10/2019
 */       
@IsTest
private class AssistanceRequestControllerTest { 
	private static final String TIMEZONE = '(GMT+10:00) Australian Eastern Standard Time (Australia/Sydney)';
	private static final String AUDCURRENCY = 'AUD - Australian Dollar';
    private static final String DRAFTING = 'Drafting';
    private static final String ESTIMATION = 'Waiting for Estimation';
    private static final String PRODNAME = 'Sales Cloud';

	@testSetup static void setupTestData() {
        
        // Create a new request for assistance
        Assistance_Request__c req = new Assistance_Request__c(
            Description__c = 'I need some help',
            Login_Access__c = 'Yes',
            Preferred_Billing_Currency__c = AUDCURRENCY,
            Preferred_Resource_Location__c = 'No preference',
            Preferred_Timezone__c = TIMEZONE,
            Prior_Stage_Name__c = null,
            Date_Required__c = Date.today().addMonths(1),
            Salesforce_Product__c = PRODNAME,
            Sandbox_Name__c = null,
            Stage_Name__c = DRAFTING,
            Success_Criteria__c = 'So I will know what to do',
            Title__c = 'Please help me',
            Urgency__c = 'Medium' 
        );
        insert req;

 	}    

    @isTest 
    static void testit() {
        Assistance_Request__c req1 = [SELECT Id FROM  Assistance_Request__c];
        String arId = req1.Id;

        Test.startTest();

        Assistance_Request__c req = AssistanceRequestController.getAssistanceRequest(arId);

        AssistanceRequestController.setNewStageNameApex(arId, ESTIMATION);

        AssistanceRequestController.pollArtisanNowApex(arId);
        AssistanceRequestController.getNameSpace();
        
        Test.stopTest();

        system.assertEquals(DRAFTING, req.Stage_Name__c);
        Assistance_Request__c req2 = [SELECT Id, Stage_Name__c FROM  Assistance_Request__c];    
        system.assertEquals(ESTIMATION, req2.Stage_Name__c);
    }  
    
}