ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/Assistance_Request__c.object-meta.xml
<CustomObject>
    <description>The Assistance Request object stores your requests for assistance using the Artisan Assistance application.</description>
    <label>Assistance Request</label>
    <nameField>
        <displayFormat>REQ{00000000}</displayFormat>
        <label>Request Ref#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/Artisan_Case_SystemModstamp__c.field-meta.xml
<CustomField>
    <fullName>Artisan_Case_SystemModstamp__c</fullName>
    <inlineHelpText>The SystemModstamp field in the Artisan Case record when last sync&#39;d</inlineHelpText>
    <label>Artisan Case SystemModstamp</label>
    <type>DateTime</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Assistance_Request__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>OR(
ISPICKVAL( Phase__c, &#39;Estimation&#39; ),
ISPICKVAL( Phase__c, &#39;Development&#39; ),
ISPICKVAL( Phase__c, &#39;Test&#39; ),
ISPICKVAL( Phase__c, &#39;Deployment&#39; ),
ISPICKVAL( Phase__c, &#39;Acceptance&#39; ),
ISPICKVAL( Stage_Name__c, &#39;Waiting for Clarification&#39; )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether the Assistance Request is still active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/classes/AssistanceRequestSchedulableBatch.cls
/**
 * Artisan Assistance - Assistance Request Schedulable Class to look for active requests on a schedule and and trigger a poll for all which are active
 * 
 * @author Richard Clarke
 * @date 29/07/2019
 */
public class AssistanceRequestSchedulableBatch implements Database.Batchable<sObject>, Schedulable {

    public static String ArtisanAssistancePollingJobName = 'Artisan Assistance Update Polling' + (Test.isRunningTest() ? ' TEST' : '');
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator('SELECT Id, Artisan_Case_SystemModstamp__c FROM Assistance_Request__c WHERE IsActive__c = true');
    }
    
    public void execute(SchedulableContext ctx) {
        // Limit the batch size to 20 to reduce the chance of hitting callout governor limits (max 100 callouts and 120 seconds in total)
        Database.executeBatch(new AssistanceRequestSchedulableBatch(), 20);
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        Set<Id> requestIds = new Set<Id>();
        for (Assistance_Request__c req : (List<Assistance_Request__c>)scope) {
            requestIds.add(req.Id);
        }
        if ( requestIds.size() > 0 ){
			System.enqueueJob(new AssistanceRequestUpdatePolling( requestIds ));
        }
    }
  
  	public void finish(Database.BatchableContext BC) {
    }
}