ArtisanAssistCode/force-app/main/default/objects/Apex_Log__c/Apex_Log__c.object-meta.xml
<CustomObject>
    <description>Used to write Apex debug and error logs</description>
    <label>Artisan Assist Apex Log</label>
    <nameField>
        <label>Apex Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artisan Assist Apex Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ArtisanAssistCode/force-app/main/default/objects/Apex_Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>Type of exception if the logs is for an exception</description>
    <inlineHelpText>Type of exception if the logs is for an exception</inlineHelpText>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Apex_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>Line Number in the code at which this log record is created</description>
    <inlineHelpText>Line Number in the code at which this log record is created</inlineHelpText>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Apex_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <description>Indicates if the log is for an exception (ERROR) or for debugging</description>
    <inlineHelpText>Indicates if the log is for an exception (ERROR) or for debugging</inlineHelpText>
    <label>Log Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Apex_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Holds exception/debug message</description>
    <inlineHelpText>Holds exception/debug message</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Apex_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Stack trace of the exception log</description>
    <inlineHelpText>Stack trace of the exception log</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/classes/LogUtilsTest.cls
/*
 * Test class for LogUtils
 *
 * @author Richard Clarke (based on prior work by Mohamed Atheek)
 * @date 15/07/2017 
 */
@isTest
private class LogUtilsTest {
	
	static testMethod void testDebugLog_Log() {
    	
        Test.startTest();
        LogUtils.log('Message1', 100, PackageInstallHandler.class);
        Test.stopTest();
        
        System.assertEquals(1, [SELECT count() FROM Apex_Log__c]);
	}
    
    class TestException extends Exception {}
    
    static testMethod void testErrorLog_LogEnabled() {
    	
    	Integer line1, line2, line3;
    	
        try {
        	throw new TestException('Message1');
        } catch (Exception e) {
        	line1 = e.getLineNumber();
        	LogUtils.addLog(e);
        }
        
        try {
        	throw new TestException('Message2');
        } catch (Exception e) {
        	line2 = e.getLineNumber();
        	LogUtils.addLog(e);
        }
        
        try {
        	throw new TestException('Message3');
        } catch (Exception e) {
        	line3 = e.getLineNumber();
        	LogUtils.addLog(e);
        }
        
        Test.startTest();

        LogUtils.commitLogsAsync();
        
        Test.stopTest();
        
        Apex_Log__c log1 = [SELECT Message__c, Line_Number__c, Log_Type__c, Exception_Type__c, Stack_Trace__c
        					FROM Apex_Log__c
        					WHERE Line_Number__c = :line1];
        System.assertEquals('Message1', log1.Message__c);
        System.assertEquals('LogUtilsTest.TestException', log1.Exception_Type__c.right(26));
        System.assertNotEquals(null, log1.Stack_Trace__c);
        System.assertEquals('ERROR', log1.Log_Type__c);
        
        Apex_Log__c log2 = [SELECT Message__c, Line_Number__c, Log_Type__c, Exception_Type__c, Stack_Trace__c
        					FROM Apex_Log__c
        					WHERE Line_Number__c = :line2];
        System.assertEquals('Message2', log2.Message__c);
        System.assertEquals('LogUtilsTest.TestException', log2.Exception_Type__c.right(26));
        System.assertNotEquals(null, log2.Stack_Trace__c);
        System.assertEquals('ERROR', log2.Log_Type__c);
        
        Apex_Log__c log3 = [SELECT Message__c, Line_Number__c, Log_Type__c, Exception_Type__c, Stack_Trace__c
        					FROM Apex_Log__c
        					WHERE Line_Number__c = :line3];
        System.assertEquals('Message3', log3.Message__c);
        System.assertEquals('LogUtilsTest.TestException', log3.Exception_Type__c.right(26));
        System.assertNotEquals(null, log3.Stack_Trace__c);
        System.assertEquals('ERROR', log3.Log_Type__c);
    }
    
    static testMethod void testErrorLog() {
    	Integer line1, line2, line3;
    	
        Test.startTest();

        try {
        	throw new TestException('Message1');
        } catch (Exception e) {
        	line1 = e.getLineNumber();
        	LogUtils.log(e);
        }
        
        Test.stopTest();
        
        Apex_Log__c log1 = [SELECT Message__c, Line_Number__c, Log_Type__c, Exception_Type__c, Stack_Trace__c
        					FROM Apex_Log__c
        					WHERE Line_Number__c = :line1];
        System.assertEquals('Message1', log1.Message__c);
        System.assertEquals('LogUtilsTest.TestException', log1.Exception_Type__c.right(26));
        System.assertNotEquals(null, log1.Stack_Trace__c);
        System.assertEquals('ERROR', log1.Log_Type__c);
    }
    
    static testMethod void testLimitChars() {    	
    	System.assertEquals(null, LogUtils.limitChars(null, 10));
    	System.assertEquals('', LogUtils.limitChars('abc', -1));
    	System.assertEquals('', LogUtils.limitChars('abc', 0));
    	System.assertEquals('a', LogUtils.limitChars('abc', 1));
    	System.assertEquals('abc', LogUtils.limitChars('abc', 10));
    	System.assertEquals('abcdefghijklmnopqrstuvwxyz', LogUtils.limitChars('abcdefghijklmnopqrstuvwxyz', 26));
    	System.assertEquals('abcdefghijklmnopqrstuvwxy', LogUtils.limitChars('abcdefghijklmnopqrstuvwxyz', 25));
    }
}