ArtisanAssistCode/force-app/main/default/objects/Apex_Log__c/Apex_Log__c.object-meta.xml
<CustomObject>
    <description>Used to write Apex debug and error logs</description>
    <label>Artisan Assist Apex Log</label>
    <nameField>
        <label>Apex Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artisan Assist Apex Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ArtisanAssistCode/force-app/main/default/objects/Apex_Log__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <description>Additional info like context variable to help in debugging the issue</description>
    <inlineHelpText>Additional info like context variable to help in debugging the issue</inlineHelpText>
    <label>Additional Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Apex_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Class in which this log record is created</description>
    <inlineHelpText>Class in which this log record is created</inlineHelpText>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Apex_Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>Type of exception if the logs is for an exception</description>
    <inlineHelpText>Type of exception if the logs is for an exception</inlineHelpText>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Apex_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>Line Number in the code at which this log record is created</description>
    <inlineHelpText>Line Number in the code at which this log record is created</inlineHelpText>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Apex_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <description>Indicates if the log is for an exception (ERROR) or for debugging</description>
    <inlineHelpText>Indicates if the log is for an exception (ERROR) or for debugging</inlineHelpText>
    <label>Log Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Apex_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Holds exception/debug message</description>
    <inlineHelpText>Holds exception/debug message</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/objects/Apex_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Stack trace of the exception log</description>
    <inlineHelpText>Stack trace of the exception log</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ArtisanAssistCode/force-app/main/default/classes/LogUtils.cls
/*
 * Artisan Assistance Utility class with methods to support logging debug messages and exceptions to a custom object
 *
 * @author Richard Clarke (based on prior work by Mohamed Atheek)
 * @date 15/07/2017 
 */
public class LogUtils {
	
	private static List<Apex_Log__c > logs = new List<Apex_Log__c >();
	
	@TestVisible
	private static String limitChars(String s, Integer maxChars) {
		return s != null ? s.substring(0, Math.min(Math.max(maxChars, 0), s.length())) : s;
	}  
	
	//saves the log message in the Apex_Log__c object
	public static void log(String message, Integer lineNumber, Type klass) {
// system.debug('***LogUtils log message: ' + message + ' lineNumber: ' + lineNumber + ', klass=' + klass.toString());
		addLog(message, lineNumber, klass);
		commitLogs();
	}
	
	//saves the log message in the Apex_Log__c object
	public static void log(Exception e) {
		log(e, '');
	}
	
	//saves the log message in the Apex_Log__c object
	public static void log(Exception e, String additionalInfo) {
// system.debug('***LogUtils log Exception e: ' + e + ' (' + additionalInfo + ')');
		addLog(e, additionalInfo);
		commitLogs();
	}
	
	//adds the log message in the log list held in memory
	public static void addLog(Exception e) {
		addLog(e, '');
	}
	
	//adds the log message in the log list held in memory
	public static void addLog(String message, Integer lineNumber, Type klass) {
// system.debug('***LogUtils addLog message: ' + message + ' (' + klass + '-' + lineNumber + ')');
        try {
            SecurityUtils.checkInsert( Apex_Log__c.getSObjectType(), new List<SObjectField> { 
                Apex_Log__c.Message__c, 
                Apex_Log__c.Line_Number__c, 
                Apex_Log__c.Class_Name__c, 
                Apex_Log__c.Log_Type__c
			});
            Apex_Log__c log = new Apex_Log__c();
            log.Message__c = limitChars(message, 32000);
            log.Line_Number__c = lineNumber;
            log.Class_Name__c = limitChars(klass != null ? klass.getName() : null, 255);
            log.Log_Type__c = 'DEBUG';
            logs.add(log);
        } catch ( Exception eCreatable ){
            system.debug('Unable to add log record in LogUtils.addLog - message: ' + message + ' (' + klass + '-' + lineNumber + ') [' + eCreatable.getMessage() + ']');
        }
	}
	
	//adds the log message in the log list held in memory
	public static void addLog(Exception e, String additionalInfo) {
// system.debug('***LogUtils addLog Exception e: ' + e + ' (' + additionalInfo + ')');
		if (e != null) {
            try {
                SecurityUtils.checkInsert( Apex_Log__c.getSObjectType(), new List<SObjectField> { 
                    Apex_Log__c.Message__c, 
                    Apex_Log__c.Additional_Info__c,
                    Apex_Log__c.Line_Number__c, 
                    Apex_Log__c.Exception_Type__c,
                    Apex_Log__c.Stack_Trace__c, 
                    Apex_Log__c.Log_Type__c 
				});
                Apex_Log__c log = new Apex_Log__c();
                log.Message__c = limitChars(e.getMessage(), 32000);
                log.Additional_Info__c = limitChars(additionalInfo, 32000);
                log.Line_Number__c = e.getLineNumber();
                log.Exception_Type__c = limitChars(e.getTypeName(), 255);
                log.Stack_Trace__c = limitChars(e.getStackTraceString(), 32000);
                log.Log_Type__c = 'ERROR';
                logs.add(log);
            } catch ( Exception eCreatable ){
	            system.debug('Unable to add log record in LogUtils.addLog - exception e: ' + e + ' (' + additionalInfo + ') [' + eCreatable.getMessage() + ']');
            }
		}
	}
	
	public static void commitLogs() {
// system.debug('***LogUtils comitLogs size: ' + logs.size());
		if (!logs.isEmpty()) {
            try {
				SecurityUtils.checkObjectIsInsertable(Apex_Log__c.getSObjectType());
                Database.insert(logs, false);
                logs.clear();
            } catch ( Exception eCreatable ){
	            system.debug('Unable to commit log records in LogUtils.commitLogs - logs ' + logs + ') [' + eCreatable.getMessage() + ']');
                logs.clear();
            }
		}
	}
	
	//saves the log list in the Apex_Log__c object in a queuable
	public static void commitLogsAsync() {
// system.debug('***LogUtils comitLogsAsync size: ' + logs.size());
		if (!logs.isEmpty()) {
			//Executing asyncronously to avoid mixed DML exception
			System.enqueueJob(new LogQueueable(logs));
		}
	}
	
	class LogQueueable implements Queueable {
		private List<Apex_Log__c > internalLogs = new List<Apex_Log__c >();	
		
	    public LogQueueable(List<Apex_Log__c > internalLogs) {
	    	this.internalLogs = internalLogs;
	    }    
	    
		public void execute(QueueableContext conext) {
			if (internalLogs != null && internalLogs.size() > 0) {
				SecurityUtils.checkObjectIsInsertable(Apex_Log__c.getSObjectType());
				Database.insert(internalLogs, false);
			}
		}
	}  
}